---
- hosts: g1
  name: Install HTTP server
  become: yes
  roles: apache 

  tasks:
    - name: Install HTTPD package 
      yum:
        name: httpd
        state: present
      
    - name: start Httpd
      service:
        name: httpd
        state: started
    

    - name: Enable Httpd
      service:
        name: httpd
        enabled: yes 
...            