---
- name: Install and configure HTTP server
  hosts: n2
  become: yes
  roles: apache 

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      
    - name: start Httpd
      service:
        name: httpd
        state: started
    

    - name: Enable Httpd
      service:
        name: httpd
        enabled: yes     