---
- name: Install HTTP server
  hosts: g1
  become: yes

  tasks:
    - name: Install HTTPD on Amazon and CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon", "CentOS"
      
    - name: Start HTTPD on Amazon and CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon", "CentOS"
    
    - name: Enable HTTPD on Amazon and CentOS
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon", "CentOS"     

    - name: Install Apache2 on Ubuntu and Debian
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu", "Debian"
      
    - name: Start Apache2 on Ubuntu and Debian
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu", "Debian"

    - name: Enable Apache2 on Ubuntu and Debian
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu", "Debian"

...