---
# tasks file for apache
---
- name: Install Apache
  package:
    name: httpd
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes
...    