---
# tasks file for apache
---
- name: Install HTTP server
  package:
    name: httpd
    state: present

- name: Start and enable HTTP server
  service:
    name: httpd
    state: started
    enabled: yes
...    